"""Turn an audit into a starting policy for `policygate`.

The gap between the two halves of agent security is a hand-written document. You audit a
server, you decide what should be allowed, and then somebody has to write the policy — and
that step is where a review turns into a wish list nobody maintains. This module generates
the first draft from the declarations, with the rule it came from and the evidence quoted
in the rationale.

Three things it is careful about:

* **It is a draft, not a decision.** Every rule is derived from what the server *says*
  about itself, and a server can say anything. The generated file opens with that warning
  and a summary of what was assumed, because a generated policy that reads like a reviewed
  one is worse than no policy: it carries the appearance of approval.
* **It fails closed.** Unclassified tools escalate; reserved-name collisions and
  instruction-carrying descriptions become explicit denies. Nothing in the output allows a
  tool merely because it was not understood.
* **It is deterministic.** No timestamps, no ordering that depends on a set — regenerating
  the same input gives the same bytes, so a diff of the policy is a diff of the server.
"""

from __future__ import annotations

import hashlib
from typing import Any

from .checks import SEVERITY_ORDER, AuditResult, Finding

HEADER = """# GENERATED by mcpaudit from a server's tool declarations. REVIEW BEFORE USE.
#
# Every rule below comes from what the server says about itself: its tool names,
# descriptions, input schemas and read/write annotations. That is a declaration, not
# behaviour, and a server can declare anything. Treat this as a first draft written to be
# argued with, not an approved policy.
#
# Assumptions it made, so you can check them one by one:
#   - tools that declare readOnlyHint and produced no findings are allowed
#   - tools that look state-changing go to a human, whether or not they admit it
#   - a tool whose description carries instruction-shaped text is denied outright
#   - a name colliding with a framework primitive is denied outright
#   - anything left unclassified escalates, because the default is to refuse
#
# Regenerate with:  mcpaudit policy <tools.json>
"""


def _rules_for(tool: dict[str, Any], findings: list[Finding]) -> tuple[str, str, str, str]:
    """Decide one tool's effect. Returns (id_suffix, effect, rationale, arg_matches)."""
    name = str(tool.get("name", ""))
    annotations = tool.get("annotations") or {}
    by_rule = {f.rule for f in findings}

    if "reserved-name-collision" in by_rule:
        return (
            "deny",
            "deny",
            (f"{name!r} collides with a name the agent framework installs outside the tool "
             "table, so it displaces a framework primitive rather than erroring. Denied "
             "until the name is changed on the server."),
            "",
        )

    instruction = next((f for f in findings if f.rule == "instruction-in-declaration"), None)
    if instruction is not None:
        return (
            "deny",
            "deny",
            ("the declaration carries instruction-shaped text, and a description is injected "
             f"into the model's context. Evidence: {instruction.evidence}"),
            "",
        )

    invisible = next((f for f in findings if f.rule == "invisible-characters"), None)
    if invisible is not None and invisible.evidence:
        return (
            "escalate",
            "escalate",
            ("the declaration contains invisible characters, which can hide instructions. "
             f"Evidence: {invisible.evidence}"),
            "",
        )

    if "destructive-declared-read-only" in by_rule:
        return (
            "escalate",
            "escalate",
            (f"{name!r} looks state-changing but declares readOnlyHint, so a client may treat "
             "it as safe. A human decides until the annotation is corrected."),
            "",
        )

    if annotations.get("readOnlyHint") is True and not findings:
        return (
            "allow",
            "allow",
            (f"{name!r} declares readOnlyHint and produced no findings in this audit — "
             "declarations only, so re-check if the server changes."),
            "",
        )

    reasons = "; ".join(sorted(by_rule)) or "no read/write annotation and no recognised shape"
    return (
        "escalate",
        "escalate",
        f"{name!r} is not classifiable as safe from its declarations ({reasons}); a human decides.",
        "",
    )


def to_policy(
    tools: list[dict[str, Any]],
    result: AuditResult,
    *,
    server: str = "",
) -> str:
    """Render a policygate-compatible TOML policy from an audit result."""
    findings_by_tool: dict[str, list[Finding]] = {}
    for finding in result.findings:
        findings_by_tool.setdefault(finding.tool, []).append(finding)

    lines: list[str] = [HEADER]
    if server:
        lines.append(f"# server: {server.replace(chr(10), ' ').replace(chr(13), ' ')}")
        lines.append("")

    lines += [
        "[gate]",
        "# Refuse anything no rule covers. This is the line that makes the rest safe.",
        'default = "escalate"',
        "consult_model = true",
        "",
    ]

    seen: set[str] = set()
    allow_count = escalate_count = deny_count = 0
    for tool in tools:
        name = str(tool.get("name", ""))
        if name in seen:
            # A duplicate name cannot have two rules with distinct ids, and policygate
            # refuses duplicate ids on load. The audit reports the duplicate; the policy
            # denies it, since which definition wins is exactly the ambiguity to avoid.
            lines.append("[[rules]]")
            lines.append(f'id = "auto-deny-duplicate-{len(seen)}"')
            lines.append('effect = "deny"')
            lines.append(f'tool = "{_escape(name)}"')
            lines.append(
                'rationale = "this name appears more than once in the server\'s tool list, '
                'so which definition is reached is ambiguous"'
            )
            lines.append("")
            deny_count += 1
            continue
        seen.add(name)

        suffix, effect, rationale, arg_matches = _rules_for(tool, findings_by_tool.get(name, []))
        rule_id = f"auto-{suffix}-{_slug(name)}"
        lines.append("[[rules]]")
        lines.append(f'id = "{rule_id}"')
        lines.append(f'effect = "{effect}"')
        lines.append(f'tool = "{_escape(name)}"')
        lines.append(f'rationale = "{_escape(rationale)}"')
        lines.append("")
        if effect == "allow":
            allow_count += 1
        elif effect == "deny":
            deny_count += 1
        else:
            escalate_count += 1

    lines.append(
        f"# {len(seen)} tool(s): {allow_count} allowed, {escalate_count} escalated to a human, "
        f"{deny_count} denied."
    )
    return "\n".join(lines) + "\n"


def _slug(name: str) -> str:
    """An ASCII rule id, and a hash when sanitising changed the name.

    The suffix matters: two different non-ASCII names can otherwise fold to the same id,
    and `policygate` refuses a policy with duplicate ids.
    """
    keep = "".join(c if (c.isascii() and (c.isalnum() or c in "-_")) else "-" for c in name)
    keep = keep.strip("-") or "tool"
    if keep != name:
        digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:6]
        return f"{keep[:40]}-{digest}"
    return keep


def _escape(text: str) -> str:
    """Escape a string for a TOML basic string.

    This is a security boundary, not formatting. The strings being written come from the
    server under audit, and an unescaped newline lets a tool name close the string and
    open its own ``[[rules]]`` block — a server rewriting the policy that governs it.
    I found exactly that while writing this file: a crafted tool name injected an
    ``effect = \"allow\"`` rule for a different tool.
    """
    out = []
    for char in text:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20 or ord(char) == 0x7F:
            out.append(f"\\u{ord(char):04X}")
        else:
            out.append(char)
    return "".join(out)


def summarise(result: AuditResult) -> str:
    counts = result.counts()
    return ", ".join(
        f"{severity} {counts[severity]}" for severity in SEVERITY_ORDER if counts[severity]
    ) or "no findings"
